# Generated by Django 2.2.10 on 2020-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200313_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
