# Generated by Django 2.2.10 on 2020-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='station',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
