# Generated by Django 2.2.10 on 2020-04-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200416_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('start_date', models.DateField(null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(null=True, verbose_name='结束日期')),
                ('found_date', models.DateField(verbose_name='创建日期')),
                ('delete_date', models.DateField(null=True, verbose_name='删除日期')),
                ('unit', models.CharField(max_length=20, null=True)),
                ('receiver_id', models.CharField(max_length=20, null=True)),
                ('receive_time', models.DateTimeField(null=True, verbose_name='签收日期')),
                ('verifier_id', models.CharField(max_length=20, null=True)),
                ('recaller_id', models.CharField(max_length=20, null=True)),
                ('status_code', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('place', models.CharField(max_length=50, null=True)),
                ('cause', models.CharField(max_length=20, null=True)),
                ('speed_limit', models.IntegerField(null=True)),
                ('speed_note', models.CharField(max_length=200, null=True)),
                ('pattern', models.CharField(max_length=200, null=True)),
                ('device', models.CharField(max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
