# Generated by Django 2.2.10 on 2020-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delete_date',
            field=models.DateField(null=True, verbose_name='删除日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recaller_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='verifier_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
