# Generated by Django 2.2.10 on 2020-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200323_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='speed_note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
