# Generated by Django 2.2.10 on 2020-04-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_item_speed_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_code',
        ),
    ]
