# Generated by Django 2.2.10 on 2020-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200403_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='end_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
